title: Défaut

tabs:
  content:
    columns:
      - width: 7/12
        icon: text
        label: Content
        fields:
          builder: fields/builder
      - width: 5/12
        icon: text
        label: Content
        sections:
          seo:
            type: fields
            fields:
              seo: fields/seo/meta
