title: Content

options:
  changeTitle: true

tabs:
  content:
    label: Pages
    columns:
      left:
        width: 1/2
        sections:
          pages:
            label: Pages
            status: all
          files: sections/gallery
      right:
        width: 1/2
        fields:
          town:
            label: Ville
            type: text
            placeholder: 'Paris'
            translate: false
          email:
            label: Email
            type: email
            translate: false
          phone:
            icon: phone
            label: Téléphone
            type: tel
            placeholder: '+33 6 00 00 00 00'
            translate: false
  meta:
    label: Meta (todo)
